--- 
user: qufotoc
cwd: /home/qufotoc/qufoto/current
log_file: log/mongrel.log
port: "40000"
config_script: config/mongrel_upload_progress.conf
environment: production
group: qufotoc
pid_file: tmp/pids/mongrel.pid
servers: 8
